name: Release

on:
  push:
    tags:
      - 'adb-keyboard-v*'

jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      working-directory: assets/adb-keyboard
    permissions:
      contents: write
      id-token: write
